# Numpy

이 문서는 cs231n강좌의 Python Numpy Tutorial 문서를 참고하여 작성되었음

Numerical python - C언어를 기반으로 한 고성능 벡터 형태 수치 계산을 위한 python library  

We can put any type in a python list.
i.e.) ['a', '123', 123, [1,2,3]]
Because python list put the variables in the memory separately, and make a link between each elements in the list.

it's based on linked list structure.

which means we cannot use spacial locallity.

But in other language we can put only specific type in the array like the array type in C language.

not like Python, we can use spacial locallity.

Python list와 비슷한 형태이나, '한 종류의 데이터'만을 담을 수 있음.
각종 vector 연산 제공  
메모리 버퍼에 배열 데이터를 저장 및 처리하여 매우 효율적인 구조를 가짐

## Numpy의 특징  
- 선형대수학, 난수기능 지원
- Broad cast 기능 지원
- N차원의 배열객체를 지원하여 범용적 데이터 처리

#### Numpy 내부 구조 관련 자료
The numpy array: structure for efficient numerical computation - IEEE computing in science and engineering 2011

### Numpy vs Python list

In [ ]:
from random import random
import time

In [ ]:
arr1 = [random() for _ in range(10000000)]
arr2 = [random() for _ in range(10000000)]

In [ ]:
start_time = time.time()
[a1+a2 for (a1, a2) in zip(arr1, arr2)]
print(time.time() - start_time)

1.3475186824798584


In [ ]:
import numpy as np

In [ ]:
narr1 = np.array(arr1)
narr2 = np.array(arr2)

In [ ]:
type(arr1), type(narr1) # python list와 numpy list의 type 비교
# numpy 속도가 넘사벽이어서 데이터 마이닝을 할때 무조건 사용

(list, numpy.ndarray)

In [ ]:
start_time = time.time()
narr1+narr2
print(time.time() - start_time)

0.047925472259521484


## Numpy 배열의 구성성분

### Shape - numpy 배열의 구조

- numpy 배열의 구조를 python tuple 자료형을 이용하여 shape으로 표현  
- 다차원 배열의 각 방향은 axis라고 부름

In [ ]:
narr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [ ]:
narr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- narr배열의 axis=0은 3, axis=1은 4

In [ ]:
narr.shape, type(narr.shape)

((3, 4), tuple)

In [ ]:
narr = np.array([1,2,3,4])
narr.shape

(4,)

### ndim - numy 배열의 차원

In [ ]:
narr.ndim

1

- axis는 dimention보다 작은 축만 존재함. 따라서 1dimention에서 axis=1은 없음

In [ ]:
narr = np.array([1,2,3,4])
narr.shape

(4,)

In [ ]:
narr = np.array([[1,2,3,4]]) # shape, dimension, axis three of them are different with above narr.
narr.shape

(1, 4)

## Numpy 배열 생성

#### python list로 부터 배열 생성

In [ ]:
arr = [1,3,5,7]
narr = np.array(arr)
narr, narr.shape, narr.ndim

(array([1, 3, 5, 7]), (4,), 1)

In [ ]:
arr = [[4,3],[8,5]]
narr = np.array(arr)
narr, narr.shape, narr.ndim

(array([[4, 3],
        [8, 5]]), (2, 2), 2)

In [ ]:
narr = np.array([[[4,3], [8,5]], [[2,6], [1,10]], [[2,6], [1,10]]])
narr, narr.shape, narr.ndim

(array([[[ 4,  3],
         [ 8,  5]],
 
        [[ 2,  6],
         [ 1, 10]],
 
        [[ 2,  6],
         [ 1, 10]]]), (3, 2, 2), 3)

#### 초기화 및 배열 생성

#### np.zeros(shape, dtype=float, order='C')  
지정된 shape의 배열을 생성하고 모든 요소를 0으로 초기화

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 4, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

#### np.ones(shape, dtype=None, order='C')  
지정된 shape의 배열을 생성하고 모든 요소를 1로 초기화

In [ ]:
np.ones((2, 4, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

#### np.full(shape, fill_value, dtype=None, order='C')  
지정된 shape의 배열을 생성하고 모든 요소를 'fill_value'로 초기화

In [ ]:
np.full((3, 2, 3), 3)

array([[[3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3]]])

#### np.eye(N, M=None, k=0, dtype=<class 'float'>)   
(N, N)을 shape으로 하는 Unit matrix 생성  
k는 정방단위행렬을 기준으로 어느 부분에 대각 행렬을 넣을지 결정

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.eye(5, k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

#### **_like 함수  
지정된 배열과 shape이 같은 배열을 생성
- np.zeros_like
- np.ones_like
- np.full_like

In [ ]:
narr

array([[[ 4,  3],
        [ 8,  5]],

       [[ 2,  6],
        [ 1, 10]],

       [[ 2,  6],
        [ 1, 10]]])

In [ ]:
np.full_like(narr, 3)

array([[[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]]])

#### np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)  
start로부터 stop범위에서 num개의 요소를 균일한 간격으로 생성한 배열 생성

In [ ]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### np.arange([start,] stop[, step,], dtype=None)  
start부터 stop미만까지 step간격으로 데이터를 생성한 배열 생성  
start와 step이 지정되지 않으면 0부터 시작하여 stop미만까지 1씩 증가하는 데이터를 생성한 배열 생성

In [ ]:
np.arange(0, 15, 3)

array([ 0,  3,  6,  9, 12])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

#### np.random.rand(shape)

shape형태의 배열을 생성하고 [0, 1)의 uniform distribution 형태로 난수를 생성하여 요소 초기화

In [ ]:
np.random.rand(4, 3)

array([[0.83964934, 0.74520578, 0.66140467],
       [0.16688516, 0.34912026, 0.92166727],
       [0.50718385, 0.46228469, 0.38623194],
       [0.3756394 , 0.74442354, 0.76341861]])

#### np.random.randn(shape)
shape형태의 배열을 생성하고 표준 정규분포(std)로 부터 난수를 생성하여 요소 초기화

In [ ]:
np.random.randn(4, 3)

array([[ 0.48548361,  0.76363271,  0.91432499],
       [-1.18042384,  0.39669191, -0.9315579 ],
       [ 1.18149504,  0.17904155,  1.33483862],
       [-2.40411297, -0.70529326,  0.10159883]])

## Numpy reshape

numpy의 shape을 변경할 수 있음.  
이때, element의 개수는 반드시 동일해야 함

In [ ]:
arr = np.arange(1, 13, 1)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr34 = arr.reshape(3, 4)  # reshape performance cost is so cheap.
#  Why?
#  넘파이는 2가지로 나눠져 버퍼메모리와 뷰
#  버퍼메모리에는 연속적인 배열이 저장되어있어
#  뷰에는 shape, axis, dim 이런것들이 저장되어 있어
#  shape, axis, dim은 사용자에게 알려주기 위한 것이 아니라
#  버퍼를 어떻게 읽을지에 대해서 지정해둔거야
#  dim은 index
#  shape은 각 index당 가질 수 있는 element의 개수
#  let shape is (3,4)
#  shape, dim, axis 숫자만 바꾸는거라서 엄청 cost가 cheap
arr34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr34[2,3] = 100
arr34

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11, 100]])

In [ ]:
arr # 주의! 원래 arr도 바뀌어
#  same buffer but differenct view
#  we just made arr34's view. not copied arr's buffer memory.

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11, 100])

#### reshape -1의 활용
-1은 해당 axis를 numpy가 자동으로 판단하게 함

In [ ]:
arr.reshape(4, -1)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10,  11, 100]])

reshape(-1, 1)은 데이터 형태를 맞추기 위하여 자주 활용됨

In [ ]:
arr34.reshape(-1,1)

array([[  1],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9],
       [ 10],
       [ 11],
       [100]])

reshape(1, -1) == flatten()

In [ ]:
arr34.flatten()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11, 100])

## Numpy indexing and slicing

In [ ]:
np.ones([3, ]).shape, np.ones([3, ]).ndim

((3,), 1)

Numpy 배열의 요소는 index배열로 참조할 수 있으며 참조 후 값의 수정이 가능함  
N차원 배열은 N개의 index로 참조 할 수 있음

In [ ]:
arr34[1, :].shape

(4,)

In [ ]:
arr, arr34

(array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11, 100]),
 array([[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11, 100]]))

In [ ]:
arr[4]

5

In [ ]:
arr34[2, 3]

100

In [ ]:
arr34[2, 3]=13
arr34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 13]])

#### slicing
:을 활용하여 여러개의 배열을 참조하는 슬라이싱을 사용  
axis별로 범위를 지정해야 하며, (from index) : (to index) 형태를 가짐  
이때 from index와 to index는 생략 가능하며, 생략시 각각 처음부터/끝까지의 의미를 가짐  
각 index는 음수를 지정가능하며, 이는 반대방향을 의미(-1은 마지막 index)

In [ ]:
arr = np.arange(1, 13, 1)
arr34 = arr.reshape(3,4)
arr, arr34

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [ ]:
arr[3:5]

array([4, 5])

In [ ]:
arr34[1:2, 1:3]

array([[6, 7]])

In [ ]:
arr34[[0,2], :]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
arr34[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [ ]:
arr34[1:-1, 1:-1]

array([[6, 7]])

In [ ]:
arr34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr34[:, [[2, 3],[1,2]]]  # Fancy indexing이라고 함
# 알면 많이 섹시해져

array([[[ 3,  4],
        [ 2,  3]],

       [[ 7,  8],
        [ 6,  7]],

       [[11, 12],
        [10, 11]]])

### Slicing 과 shape 유의점

In [ ]:
arr34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr34[:, 1]

array([ 2,  6, 10])

In [ ]:
arr34[:, 1].shape

(3,)

In [ ]:
np.dot(arr34[:, 1], np.ones([1,3])) # Error!

ValueError: ignored

In [ ]:
np.dot(np.ones([1,3]), np.ones([1,3]))

In [ ]:
print(arr34[:, 1].reshape(3,1))
print(np.ones([1,3]))
np.dot(arr34[:, 1].reshape(3, 1), np.ones([1,3]))

In [ ]:
np.dot(arr34[:, 1], np.ones([3,1]))

### Boolean numpy indexing and masking

배열의 각 요소가 조건을 만족하는지 true/false 지정하는 방식

In [ ]:
arr34

In [ ]:
bool_index = (arr34 > 6)
bool_index

Mask 배열은 boolean값으로 이루어진 배열로, 동일한 shape을 가지는 다른 배열의 index로 활용할 수 있다.   
Mask indexing을 수행한 결과는 mask 배열의 True인 요소만이 추출된 1차원 배열로 나타남

In [ ]:
arr34[bool_index]

#### 열 indexing

In [ ]:
arr34[:, 2]>5

In [ ]:
arr34[arr34[:, 2]>5]

## Numpy 배열 연산

In [ ]:
arr1 = np.arange(1, 25, 2).reshape(3, -1)
arr2 = np.arange(23, 0, -2).reshape(3, -1)

In [ ]:
arr1, arr2

### 기본 사칙연산

Numpy는 python 기본연산자를 재정의하여 배열에 대한 직관성을 확보함

In [ ]:
arr1 + arr2

In [ ]:
arr1 - arr2

In [ ]:
arr1 / arr2

In [ ]:
arr1 * arr2

In [ ]:
arr1 % arr2

### 내적

In [ ]:
np.dot(arr1, arr2.reshape(4, -1))

### 배열간 비교

In [ ]:
arr1 == arr2

In [ ]:
arr1 > arr2

두 배열이 완전히 동일한지 비교

In [ ]:
np.array_equal(arr1, arr2)

## Aggregate function

numpy는 배열의 합, 평균, 최대/최소값등의 함수를 제공함.
이 함수들은 axis를 기준으로 계산됨

In [ ]:
arr = np.arange(0, 32).reshape([4,2,4])

In [ ]:
print(arr.shape)
arr

In [ ]:
arr.sum()

In [ ]:
arr.sum(axis=0)
# 괄호를 기준으로 axis를 생각해라
# 첫번째 괄호 무시하고 가장 바깥쪽 괄호가 axis 0
# 두번째 괄호가 axis 1
# 세번째 괄호가 axis 2

In [ ]:
arr.sum(axis=(1, 2))

In [ ]:
arr.sum(axis=1)

In [ ]:
arr.sum(axis=2)

배열의 평균, min, max도 비슷하게 동작함

In [ ]:
arr.mean(), arr.min(), arr.max()

In [ ]:
print(arr.mean(axis=0))
print(arr.min(axis=1))
print(arr.max(axis=2))

### index 찾기 - arg function

In [ ]:
arr = np.arange(6).reshape(2,3) + 10
arr

In [ ]:
arr.max(), arr.argmax()

In [ ]:
arr.min(), arr.argmin()

### np.where

In [ ]:
arr

In [ ]:
np.where(arr==12)

In [ ]:
np.where(arr<15)

#### Slicing with where

In [ ]:
arr[np.where(arr<12)]

In [ ]:
arr[arr<12]

#### Replace with where

In [ ]:
np.where(arr<12, 0, arr)

In [ ]:
np.where(arr<12, arr*10, arr*0.1)

#### 구체적인 index를 찾고싶을 때

In [ ]:
np.unravel_index(np.argmax(arr), arr.shape)

## Numpy broadcasting

Numpy는 shape이 다른 두 배열에 대한 연산을 지원함  
두 배열의 shape을 임의로 조절하여 연산을 수행

In [ ]:
arr = np.arange(0, 12).reshape(3,4)
arr

In [ ]:
arr + 3

In [ ]:
arr1 = np.arange(5).reshape(1, 5)
arr2 = np.arange(5).reshape(5, 1)
arr1, arr2

In [ ]:
arr1 + arr2

## np.unique

In [ ]:
l = [0] * 5 + [1] * 5
print(l)
a = np.array([0] * 5 + [1] * 5)
a = a.reshape(5, 2)
a

In [ ]:
np.unique(a)

In [ ]:
np.unique(a, return_counts=True)

## np.concatenate((a1, a2, ...), axis=0, out=None)
a1, a2를 axis를 기준으로 병합  
이때 병합되는 array들은 기준이 되는 axis를 제외하고는 모두 동일한 dimension을 가져야 함

In [62]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a, b,

(array([[1, 2],
        [3, 4]]), array([[5, 6]]), (2, 2))

In [59]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [61]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

#### dimension (1, 5)와 (5,)는 다름을 인식하고 활용하여야 함

In [ ]:
a = np.ones([1, 5])
b = np.ones([5,])
c = np.zeros([1, 5])
a, b, c

In [ ]:
np.concatenate((a, c), axis=0)

In [ ]:
np.concatenate((b, c), axis=0)

In [ ]:
b.shape

In [ ]:
a.shape